[build-system]
# For some reason, not including the minimum version bound
# causes pip to not install setuptools at all?
# At least, when giving `setuptools` without a version,
# I get an error that it can't find module `distutils`
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyCIF"
version = "0.0.0"
description = """\
Collaborative CAD platform for \
hierarchical design of on-chip imaging devices\
"""
authors = [
	{name = "Nikita Soshnin", email = "n.a.soshnin@student.tudelft.nl"}
	]
license = { text = "I haven't decided yet" }
readme = "README.md"
classifiers = [
	'Programming Language :: Python :: 3',
	]
requires-python = ">=3"
dependencies = [
	'numpy',
	]

[tool.setuptools.packages.find]
# For some reason setuptools is angry
# about the `img` directory, even thought
# it has no `__init__.py` ???
# Need to tell it explicitly
# what packages to include.
# This could theoretically be avoided by switching
# to src-layout, but I don't want to ._.
include = [ "PyCIF", "PyCIF.*" ]

